# Generated by Django 4.2.6 on 2023-10-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=20, verbose_name='Room rank')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Room number')),
                ('full', models.BooleanField(default=False, verbose_name='Full or not')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
                ('picture_1', models.ImageField(blank=True, null=True, upload_to='documents', verbose_name='Picture num 1')),
                ('picture_2', models.ImageField(blank=True, null=True, upload_to='documents', verbose_name='Picture num 2')),
                ('picture_3', models.ImageField(blank=True, null=True, upload_to='documents', verbose_name='Picture num 3')),
                ('options', models.TextField(blank=True, null=True, verbose_name='Options')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Room.roomrank', verbose_name='Room rank')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start reservation')),
                ('end', models.DateTimeField(verbose_name='End reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.room', verbose_name='Room number')),
            ],
        ),
    ]
