# Generated by Django 4.2.6 on 2023-10-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_room_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
